# Generated by Django 4.0.1 on 2024-07-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0003_project_alter_clients_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='shoot_start_data',
            new_name='shoot_start_date',
        ),
    ]
