# Generated by Django 4.0.1 on 2024-07-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0004_rename_amount_project_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clients',
            new_name='Client',
        ),
    ]
