# Generated by Django 4.0.1 on 2024-07-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0007_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='note',
        ),
    ]
