# Generated by Django 4.0.1 on 2024-07-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0009_assets_project_outsourcing_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='buy_price',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
        migrations.AlterField(
            model_name='assets',
            name='quantity',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
        migrations.AlterField(
            model_name='assets',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
