# Generated by Django 4.0.1 on 2024-07-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0010_alter_assets_buy_price_alter_assets_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='outsourcing_amt',
            field=models.IntegerField(default=0),
        ),
    ]
