# Generated by Django 4.0.1 on 2024-07-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0011_alter_project_outsourcing_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pending_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
