# Generated by Django 4.0.1 on 2024-07-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0013_project_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='count',
        ),
    ]
