# Generated by Django 4.0.1 on 2024-07-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0029_entertainment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
