# Generated by Django 4.0.1 on 2024-07-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0030_alter_entertainment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense',
            new_name='project_expense',
        ),
    ]
