# Generated by Django 4.0.1 on 2024-07-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0031_rename_expense_expense_project_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='project_code',
            field=models.TextField(blank=True),
        ),
    ]
