# Generated by Django 4.0.1 on 2024-07-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0032_alter_expense_project_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='income',
            new_name='project_income',
        ),
    ]
