# Generated by Django 4.0.1 on 2024-08-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0041_alter_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='outsourcing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='received_amt',
            field=models.IntegerField(default=0),
        ),
    ]
