# Generated by Django 4.0.1 on 2024-08-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0043_alter_project_outsourcing_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='project_code',
            field=models.TextField(blank=True),
        ),
    ]
