# Generated by Django 4.0.1 on 2024-08-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0045_alter_expense_project_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='expenses',
        ),
    ]
