# Generated by Django 4.0.1 on 2024-08-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0049_alter_income_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='project_code',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='income_income', to='cymaticsapp.project'),
        ),
    ]
