# Generated by Django 4.0.1 on 2024-08-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0052_alter_income_project_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='project_code',
        ),
    ]
