# Generated by Django 4.0.1 on 2024-08-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0054_income_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
