# Generated by Django 5.1 on 2024-09-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0057_alter_assets_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='out_client',
            field=models.CharField(default='prabu', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='out_for',
            field=models.CharField(default='photo', max_length=100),
        ),
    ]
