# Generated by Django 5.1 on 2024-09-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0058_project_out_client_project_out_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='out_client',
            field=models.CharField(blank=True, default='prabu', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='out_for',
            field=models.CharField(blank=True, default='photo', max_length=100),
        ),
    ]
