# Generated by Django 5.1 on 2024-09-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0060_project_latitude_project_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='project_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='project_income',
            field=models.BooleanField(default=False),
        ),
    ]
