# Generated by Django 5.1 on 2024-09-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0061_alter_expense_project_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='out_comp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='out_num',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
