# Generated by Django 5.1 on 2024-09-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0062_project_out_comp_project_out_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='out_client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='out_for',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
